image: library/haskell:8.6.5

# TODO fix the build, it's failing in CI

# TODO matrix build
# https://docs.gitlab.com/ce/ci/yaml/README.html

build_job:
  stage: build
  script:
    - apt-get update -qq && apt-get install -y python
    - cabal v2-update
    - ./tests.sh
