cabal-version:       2.2
name:                hsinspect
version:             0.0.1
synopsis:            Inspect Haskell source files.
license:             GPL-3.0-or-later
license-file:        LICENSE
author:              Tseen She
maintainer:          Tseen She
copyright:           2019 Tseen She
bug-reports:         https://gitlab.com/tseenshe/hsinspect/merge_requests
tested-with:         GHC ^>= 8.4.4 || ^>= 8.6.5
category:            Building
description:
  Inspect @.hs@ files using the ghc api.

-- https://www.haskell.org/cabal/users-guide/cabal-projectindex.html

common deps
  -- Controversial: we don't bound any dependencies because we only
  -- depend on installed things that come with ghc.
  build-depends:    base
                  , ghc
                  -- TODO remove ghc-paths, it's on hackage
                  , ghc-paths
  ghc-options:      -Wall
                    -Werror=missing-home-modules
  default-language: Haskell2010

executable hsinspect
  import:             deps
  hs-source-dirs:     exe
  main-is:            Main.hs
  ghc-options:        -threaded

library
  import:             deps
  hs-source-dirs:     library
  exposed-modules:    HsInspect.Imports

test-suite            tests
  import:             deps
  hs-source-dirs:     tests
  type:               exitcode-stdio-1.0
  main-is:            Driver.hs
  build-depends:    , tasty            ^>= 1.1.0.4
                    , tasty-hspec      ^>= 1.1.5
                    , tasty-quickcheck ^>= 0.10
  build-tool-depends: tasty-discover:tasty-discover ^>= 4.2.1
  ghc-options:        -threaded
