cabal-version: 2.2
name:          medley
version:       0.0.1

flag uncompilable
  description: Enables invalid code (user input)
  manual:      True
  default:     True

flag ghcflags
  description: Generate .ghc.flags files during compilation
  manual:      True
  default:     False

common deps
  build-depends:    base
  ghc-options:      -Werror=missing-home-modules
  default-language: Haskell2010

  if flag(uncompilable)
    cpp-options: -DUNCOMPILABLE

  if flag(ghcflags)
    ghc-options: -fplugin GhcFlags.Plugin
    build-depends: ghcflags

library
  import:          deps
  hs-source-dirs:  library
  build-depends:   contravariant ^>=1.5.2
  exposed-modules:
    Medley.Wibble
    Medley.Wobble
