cabal-version:       2.2
name:                medley
version:             0.0.1

flag uncompilable
  description: Enables invalid code (user input)
  manual: True
  default: True

common deps
  build-depends:    base
  ghc-options:      -Werror=missing-home-modules
  default-language: Haskell2010
  if flag(uncompilable)
    cpp-options:      -DUNCOMPILABLE

library
  import:             deps
  hs-source-dirs:     library
  build-depends:      contravariant ^>= 1.5.2
                    , hsinspect
                    -- ^ users can inject via ghc-options, but it's difficult to wire up inplace modules
  exposed-modules:    Medley.Wibble
                    , Medley.Wobble
